# Generated by Django 4.1.4 on 2023-01-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "investimento",
            "0002_ativo_instituicaofinanceira_posicaodata_perfil_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExtratoOperacoes",
            new_name="ExtratoOperacao",
        ),
    ]
