# Generated by Django 4.1.4 on 2023-01-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investimento", "0003_rename_extratooperacoes_extratooperacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BRD_CUSTO",
                    models.DecimalField(decimal_places=4, default=1.0038, max_digits=8),
                ),
            ],
        ),
    ]
