# Generated by Django 4.2.8 on 2023-12-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0003_remove_classeativo_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativoperfilcaixa',
            name='caixa_alocacao',
        ),
    ]
