# Generated by Django 4.1.4 on 2023-01-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investimento", "0004_parametro"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametro",
            name="E_MAIL_API",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
