# Generated by Django 4.2.8 on 2023-12-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0005_remove_ativoperfilcaixa_alocacao_teorica_valor_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativoperfilcaixa',
            old_name='alocacao_teorica_percentual',
            new_name='aloc_teor_percent_caixa',
        ),
        migrations.AddField(
            model_name='ativoperfilcaixa',
            name='aloc_teor_percent_carteira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
