# Generated by Django 4.2.8 on 2023-12-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0006_rename_alocacao_teorica_percentual_ativoperfilcaixa_aloc_teor_percent_caixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratooperacao',
            name='ir_fonte',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='extratooperacao',
            name='operacao',
            field=models.CharField(choices=[('VENDA', 'Venda'), ('COMPRA', 'Compra'), ('SUBSCRIÇÃO', 'Subscrição'), ('DESDOBRO', 'Desdobro')], max_length=10),
        ),
    ]
