# Generated by Django 4.1.4 on 2023-01-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investimento", "0006_remove_ativo_alocacao_caixa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extratooperacao",
            name="ativo_perfil_caixa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operacoes",
                to="investimento.ativoperfilcaixa",
            ),
        ),
    ]
