# Generated by Django 4.2.2 on 2023-06-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0008_alter_ativo_cnpj_alter_ativo_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='cnpj',
            field=models.CharField(blank=True, default='', help_text='CNPJ do ativo', max_length=19),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='ticket',
            field=models.CharField(blank=True, default='', help_text='Código de negociação do ativo na bolsa', max_length=10),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='ticket_original',
            field=models.CharField(blank=True, default='', help_text='Código de negociação original do ativo (somente BRDs)', max_length=10),
        ),
    ]
