# Generated by Django 4.2.8 on 2024-01-27 01:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0009_ativo_cota_bolsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicaodata',
            name='dividendos',
        ),
        migrations.AddField(
            model_name='ativo',
            name='dividendos',
            field=models.BooleanField(default=False, help_text='O ativo distribui dividendos?'),
        ),
        migrations.AlterField(
            model_name='posicaodata',
            name='cota_ativo_quantidade',
            field=models.DecimalField(decimal_places=10, default=0, help_text='cotas do ativo, disponibilizada na corretora', max_digits=15),
        ),
        migrations.AlterField(
            model_name='posicaodata',
            name='cota_sistema_quantidade',
            field=models.DecimalField(decimal_places=10, default=0, help_text='quantidade de cotas calculadas pelo sistema', max_digits=15),
        ),
        migrations.AlterField(
            model_name='posicaodata',
            name='cota_sistema_valor',
            field=models.DecimalField(decimal_places=4, default=0, help_text='valor cota do sistema', max_digits=19),
        ),
        migrations.CreateModel(
            name='PosicaoDataBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('cota_valor', models.DecimalField(decimal_places=4, default=0, help_text='valor cota na bolsa', max_digits=19)),
                ('cota_valor_dolar', models.DecimalField(decimal_places=4, default=0, help_text='valor em dolar da cota na bolsa', max_digits=19)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posicoesBolsa', to='investimento.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Dividendos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('dividendos', models.DecimalField(decimal_places=4, default=0, help_text='valor dividendos recebidos', max_digits=19)),
                ('ativo_perfil_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividendos', to='investimento.ativoperfilcaixa')),
            ],
        ),
    ]
