# Generated by Django 4.2.5 on 2023-09-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0010_instituicaofinanceira_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='alocacao_teorica_valor_currency',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='cota_sistema_valor_currency',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='alocacao_teorica_valor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='cota_sistema_valor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
