# Generated by Django 4.2.8 on 2024-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0011_posicaodatafundo_alter_ativo_desdobramento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratooperacao',
            name='operacao',
            field=models.CharField(choices=[('VENDA', 'Venda'), ('COMPRA', 'Compra'), ('SUBSCRIÇÃO', 'Subscrição'), ('DESDOBRO', 'Desdobramento')], max_length=10),
        ),
    ]
